# -*- coding: utf-8 -*-
"""인턴지원_해설

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0twnCllHu37rPAnnYljBvpmRQe44hes
"""

import requests
import json

def clean(v, filters):
  if isinstance(v, dict):
    return {k: clean(val, filters) for k, val in v.items()
    if not (isinstance(val, str) and val in filters)}

  if isinstance(v, list):
    return [clean(i, filters) for i in v
    if not (isinstance(i, str) and i in filters)]

  return v

def clean_data():
  filters = {"N/A", "-",""}
  r = requests.get('https://coderbyte.com/api/challenges/json/json-cleaning')
  varsa = clean(r.json(), filters)
  return json.dumps(varsa)

print(clean_data())

def HTMLElements(strParam):
  taglist = []
  i, n=0, len(strParam)
  while i<n:
    if strParam[i] == '<':
      j = strParam.find('>', i+1)
      if j == -1:
        break
      taglist.append(strParam[i+1:j])
      i = j+1
    else:
      i+=1

  stack = []
  var0cg = None

  for tag in taglist:
    if not tag.startswith('/'):
      stack.append(tag)
    else:
      name = tag[1:]
      if not stack:
        varOcg = name
        return name
      top = stack[-1]
      if top != name:
        varOcg = top
        return top
      stack.pop()

  if stack:
    varOcg = stack[0]
    return stack[0]

  varOcg = "true"
  return "true"

# keep this function call here
print(HTMLElements(input()))

import ast

def BE2ndDiagonal(strArr):
    if isinstance(strArr, str):
        varFiltersCg = ast.literal_eval(strArr)
    else:
        varFiltersCg = strArr

    matrix = [ast.literal_eval(row) if isinstance(row, str) else row
              for row in varFiltersCg]

    varOcg = []
    R = len(matrix)
    C = len(matrix[0]) if R > 0 else 0

    for sc in range(C):
        r, c = 0, sc
        while r < R and c >= 0:
            varOcg.append(matrix[r][c])
            r += 1
            c -= 1

    for sr in range(1, R):
        r, c = sr, C - 1
        while r < R and c >= 0:
            varOcg.append(matrix[r][c])
            r += 1
            c -= 1

    return ", ".join(map(str, varOcg))

# keep this function call here
print(BE2ndDiagonal(input()))
